###
GET http://localhost:13000/


### // SETUP DATABASE
GET http://localhost:13000/setup

###
POST http://localhost:13000/clear

### // INSERT
POST http://localhost:13000/insert
Content-Type: application/json

{
  "user": {
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@example.com",
    "password": "$2a$10$xJwLH5XZ1z3QbB7p6YvT.eq1RZKU9dL4VcBgdWZ2MsDhRJ5JQzF6O",
    "phone_number": "+1234567890",
    "country_code": "+1",
    "verification_code": "ABC123",
    "license_number": "DL12345678",
    "is_admin": false,
    "is_banned": false,
    "balance": 1500.75
  },
  
  "booking": {
    "location": "Downtown Parking",
    "spacenumber": 42,
    "isblocked": false,
    "date": "2025-05-15",
    "time": "14:30:00",
    "isverified": true
  },
  "parkingLot": {
    "capacity": 200
  }
}
